# Generated by Django 5.0.6 on 2024-06-11 08:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('video', models.FileField(upload_to='videos/')),
                ('thumbnail_url', models.URLField()),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('publish_time', models.TimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.category')),
            ],
            options={
                'db_table': 'NewsVideo',
            },
        ),
    ]
