# Generated by Django 5.0.6 on 2024-06-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsvideo',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsvideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
